languageCode = "zh-cn"
title = "shuirong"
theme = "yinyang"
defaultContentLanguage = "zh"
author = "shuirong"


[languages]
[languages.zh]
contentDir = "content/zh"
languageName = "Chinese"
weight = 1
[languages.ja]
contentDir = "content/ja"
languageName = "Japanese"
weight = 2

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
guessSyntax = true
noClasses = true
style = "bw"
tabWidth = 4

[params]
mainSections = ["posts"]
headTitle = "shuirong"
# extraHead = '<script async src="https://www.googletagmanager.com/gtag/js?id=UA-xxx"></script>'
# [[params.socials]]
# name = "About Me"
# link = "https://joway.io"
[[params.socials]]
name = "Github"
link = "https://github.com/shuiRong"
# postHeaderContent = ""
# postFooterContent = "<br/><br/><p>Subscribe to：<a target='_blank' href='https://mailchi.mp/a1a0d59e7a19/joway'>Joway's Blog</a></p>"
# extraCSSFiles = ["css/foo.css", "css/bar.css"]
extraCSSFiles = []
